require('dotenv').config()
const express =require('express')
const app =express()
const cors = require('cors')
const counterRoutes = require ('./Routers/counterRoutes')
const departmentRoutes = require('./Routers/departmentRouter')
const studentsRoutes = require('./Routers/studentRouters')
const staffRoutes=require('./Routers/staffRoutes')
const courseRoutes= require('./Routers/courseRoutes')
const timeSlotRoutes= require('./Routers/timeSlotRoutes')
const courseAllocationRoutes= require('./Routers/courseAllocation')
const timeTableRoutes= require('./Routers/timeTableRouter')
const huggingFaceRoutes = require('./Routers/huggingFaceTestingRoute')
const assignmentRoutes= require('./Routers/assignmentRoutes')
const assignmentTopicRoutes=require('./Routers/assignmentTopicRoutes')
const {databaseConnection}=require('./utils/db.connection')
// const assignmentCreationAgent = require('./Automation/assignmentCreationAgentCall')
app.use(express.json())
app.use(cors())
app.use('/api',counterRoutes)
app.use('/api',departmentRoutes)
app.use('/api',studentsRoutes)
app.use('/api',staffRoutes)
app.use('/api',courseRoutes) 
app.use('/api',timeSlotRoutes)
app.use('/api',courseAllocationRoutes)
app.use('/api',timeTableRoutes)
app.use('/api',assignmentRoutes)
app.use('/api',assignmentTopicRoutes)
app.use('/huggingFace',huggingFaceRoutes)
const port=process.env.Port

// assignmentCreationAgent()
app.listen(port,async()=>{
    await databaseConnection()
    console.log("App Listen on Port ",port)
})