import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Badge } from './ui/badge';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from './ui/select';
import {
  FileText,
  Download,
  Calendar,
  TrendingUp,
  DollarSign,
  Users,
  CheckCircle,
} from 'lucide-react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

export function ReportSection() {
  const [selectedMonth, setSelectedMonth] = useState('current');
  const [autoGeneratedReports, setAutoGeneratedReports] = useState([]);

  // (Simulated data remains the same)
  useEffect(() => {
    const reports = [
      {
        id: 1,
        title: 'January 2026 Monthly Report',
        date: '2026-02-01',
        status: 'Generated',
        revenue: '$42,150',
        newSubscriptions: 15,
        churnRate: '2.3%',
        highlights: [
          'Revenue increased by 15% compared to December',
          '15 new institutes subscribed',
          'Average subscription value: $2,810',
        ],
      },
      // ... id 2 and 3
    ];
    setAutoGeneratedReports(reports);
  }, []);

  const monthlyComparison = [
    { month: 'Jul', revenue: 32000, users: 8500 },
    { month: 'Aug', revenue: 34000, users: 9200 },
    { month: 'Sep', revenue: 36000, users: 9800 },
    { month: 'Oct', revenue: 38000, users: 10500 },
    { month: 'Nov', revenue: 38900, users: 11200 },
    { month: 'Dec', revenue: 36650, users: 11800 },
    { month: 'Jan', revenue: 42150, users: 12456 },
  ];

  const currentMonthStats = {
    totalRevenue: '$42,150',
    newInstitutes: 15,
    activeUsers: 12456,
    churnRate: '2.3%',
    averageSubscriptionValue: '$2,810',
    renewalRate: '94.7%',
  };

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-7xl mx-auto">
      {/* Header Section */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Reports & Analytics</h2>
          <p className="text-gray-500 text-sm md:text-base">
            Auto-generated monthly reports and comprehensive analytics
          </p>
        </div>
        <div className="flex flex-col sm:flex-row gap-3">
          <Select value={selectedMonth} onValueChange={setSelectedMonth}>
            <SelectTrigger className="w-full sm:w-[180px]">
              <SelectValue placeholder="Select Period" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="current">Current Month</SelectItem>
              <SelectItem value="last">Last Month</SelectItem>
              <SelectItem value="quarter">Last Quarter</SelectItem>
              <SelectItem value="year">Last Year</SelectItem>
            </SelectContent>
          </Select>
          <Button className="w-full sm:w-auto bg-blue-600 hover:bg-blue-700">
            <Download className="w-4 h-4 mr-2" />
            Export Report
          </Button>
        </div>
      </div>

      {/* KPI Stats Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
        <StatCard 
          icon={<DollarSign className="w-6 h-6" />} 
          title="Total Revenue" 
          value={currentMonthStats.totalRevenue} 
          color="bg-green-50 text-green-600" 
        />
        <StatCard 
          icon={<TrendingUp className="w-6 h-6" />} 
          title="New Institutes" 
          value={currentMonthStats.newInstitutes} 
          color="bg-blue-50 text-blue-600" 
        />
        <StatCard 
          icon={<Users className="w-6 h-6" />} 
          title="Active Users" 
          value={currentMonthStats.activeUsers} 
          color="bg-purple-50 text-purple-600" 
          className="sm:col-span-2 lg:col-span-1" // Mobile logic: spans 2 on tablet to fill row
        />
      </div>

      {/* Charts Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ChartCard title="Revenue Trend (7 Months)">
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={monthlyComparison} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} />
              <XAxis dataKey="month" fontSize={12} tickLine={false} axisLine={false} />
              <YAxis fontSize={12} tickLine={false} axisLine={false} />
              <Tooltip cursor={{fill: '#f3f4f6'}} />
              <Bar dataKey="revenue" fill="#3b82f6" radius={[4, 4, 0, 0]} name="Revenue ($)" />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="User Growth Trend">
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={monthlyComparison} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} />
              <XAxis dataKey="month" fontSize={12} tickLine={false} axisLine={false} />
              <YAxis fontSize={12} tickLine={false} axisLine={false} />
              <Tooltip />
              <Line type="monotone" dataKey="users" stroke="#10b981" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 6 }} name="Total Users" />
            </LineChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      {/* Reports List */}
      <Card className="shadow-sm">
        <CardHeader className="p-4 md:p-6 border-b">
          <CardTitle className="flex items-center gap-2 text-lg">
            <FileText className="w-5 h-5 text-blue-600" />
            Auto-Generated Monthly Reports
          </CardTitle>
          <p className="text-xs md:text-sm text-gray-500">Reports are automatically generated on the 1st of each month</p>
        </CardHeader>
        <CardContent className="p-4 md:p-6 space-y-6">
          {autoGeneratedReports.map((report) => (
            <div key={report.id} className="border border-gray-100 rounded-xl p-4 md:p-5 hover:border-blue-200 transition-colors shadow-sm bg-white">
              <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3 mb-4">
                <div className="space-y-1">
                  <h4 className="font-bold text-gray-900 md:text-lg">{report.title}</h4>
                  <p className="text-xs text-gray-500 flex items-center gap-1.5">
                    <Calendar className="w-3.5 h-3.5" /> Generated on {report.date}
                  </p>
                </div>
                <Badge className="bg-green-50 text-green-700 border-green-200 w-fit">
                  <CheckCircle className="w-3 h-3 mr-1" /> {report.status}
                </Badge>
              </div>

              {/* Data Summary Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-4">
                <ReportMetric label="Revenue" value={report.revenue} />
                <ReportMetric label="New Subs" value={report.newSubscriptions} />
                <ReportMetric label="Churn Rate" value={report.churnRate} color="text-red-600" />
              </div>

              {/* Highlights Box */}
              <div className="bg-slate-50 rounded-lg p-3 md:p-4 mb-4">
                <p className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">Key Highlights</p>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-1">
                  {report.highlights.map((highlight, idx) => (
                    <li key={idx} className="text-sm text-slate-600 flex items-start gap-2">
                      <span className="text-blue-500 mt-1">•</span>
                      {highlight}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-wrap gap-2">
                <Button variant="outline" size="sm" className="flex-1 sm:flex-none">
                  <FileText className="w-4 h-4 mr-2" /> View Full
                </Button>
                <Button variant="outline" size="sm" className="flex-1 sm:flex-none">
                  <Download className="w-4 h-4 mr-2" /> PDF
                </Button>
              </div>
            </div>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}

// Sub-components for cleaner code and easier responsive management
function StatCard({ icon, title, value, color, className }) {
  return (
    <Card className={className}>
      <CardContent className="p-5 flex items-center gap-4">
        <div className={`${color} p-3 rounded-xl`}>{icon}</div>
        <div>
          <p className="text-xs font-medium text-gray-500 uppercase tracking-tight">{title}</p>
          <p className="text-xl md:text-2xl font-bold text-gray-900">{value}</p>
        </div>
      </CardContent>
    </Card>
  );
}

function ChartCard({ title, children }) {
  return (
    <Card className="overflow-hidden">
      <CardHeader className="p-4 border-b bg-gray-50/50">
        <CardTitle className="text-base font-semibold">{title}</CardTitle>
      </CardHeader>
      <CardContent className="p-4">{children}</CardContent>
    </Card>
  );
}

function ReportMetric({ label, value, color = "text-gray-900" }) {
  return (
    <div className="bg-gray-50/50 border border-gray-100 rounded-lg p-3 text-center sm:text-left">
      <p className="text-[10px] md:text-xs text-gray-500 font-medium uppercase">{label}</p>
      <p className={`text-base md:text-xl font-bold ${color}`}>{value}</p>
    </div>
  );
}